[[LibTAPITblgen]]
arch = "x86_64"
git-tree-sha1 = "912feebf125d8dc10cfa41b4e3bcf159a3beb615"
libc = "glibc"
os = "linux"

    [[LibTAPITblgen.download]]
    sha256 = "56ae5429cf3aae206fbba2b593812665d057e7b5621d281788f5479891088c28"
    url = "https://github.com/staticfloat/LibTAPITblgen_jll.jl/releases/download/v1300.6.0-GCCBootstrap-x86_64-linux-gnu/LibTAPITblgen-v1300.6.0-x86_64-linux-gnu.tar.gz"

[[LibTAPITblgen-build_log]]
arch = "x86_64"
git-tree-sha1 = "f505e19077016d6d6dad6a55cd321260982d6494"
lazy = true
libc = "glibc"
os = "linux"

    [[LibTAPITblgen-build_log.download]]
    sha256 = "65c6a091a455c890e08a740b7fa133da10e0736a124ccd39972295bbfefe91a2"
    url = "https://github.com/staticfloat/LibTAPITblgen_jll.jl/releases/download/v1300.6.0-GCCBootstrap-x86_64-linux-gnu/LibTAPITblgen-build_log-v1300.6.0-x86_64-linux-gnu.tar.gz"

[[LibTAPITblgen-extract_log]]
arch = "x86_64"
git-tree-sha1 = "1af39c41ad4e2a8db216f8ab13d8307dfa8bcb2c"
lazy = true
libc = "glibc"
os = "linux"

    [[LibTAPITblgen-extract_log.download]]
    sha256 = "33dadb4d8bd091a146f5c55fb6a613b9d89b916e8295747d988927e671d20208"
    url = "https://github.com/staticfloat/LibTAPITblgen_jll.jl/releases/download/v1300.6.0-GCCBootstrap-x86_64-linux-gnu/LibTAPITblgen-extract_log-v1300.6.0-x86_64-linux-gnu.tar.gz"
