[[LibTAPITblgen]]
arch = "x86_64"
git-tree-sha1 = "0b45f8cc86df5a654e9ad370a61f143893cdaf07"
libc = "glibc"
os = "linux"

    [[LibTAPITblgen.download]]
    sha256 = "26fb36a04c9d63509ff9f8fb636d5bdba29fbe4512d5df2ae9012920915cfadb"
    url = "https://github.com/staticfloat/LibTAPITblgen_jll.jl/releases/download/v1300.6.1-GCCBootstrap-x86_64-linux-gnu/LibTAPITblgen-v1300.6.1-x86_64-linux-gnu.tar.gz"

[[LibTAPITblgen-build_log]]
arch = "x86_64"
git-tree-sha1 = "058defa83f2aee17c7ac56be64bc67a5943c79e0"
lazy = true
libc = "glibc"
os = "linux"

    [[LibTAPITblgen-build_log.download]]
    sha256 = "172f68cca6e339bdc5fe998c94cb5d6396c3fd75f9c8f8f119d08cb8dd785a1e"
    url = "https://github.com/staticfloat/LibTAPITblgen_jll.jl/releases/download/v1300.6.1-GCCBootstrap-x86_64-linux-gnu/LibTAPITblgen-build_log-v1300.6.1-x86_64-linux-gnu.tar.gz"

[[LibTAPITblgen-extract_log]]
arch = "x86_64"
git-tree-sha1 = "df48b49ce2b5ba899b030350c4424e5591ca0f32"
lazy = true
libc = "glibc"
os = "linux"

    [[LibTAPITblgen-extract_log.download]]
    sha256 = "6ae86e00db53ecb534d09a183d8d15cffb980bcfec1052557b930f0b0cff3409"
    url = "https://github.com/staticfloat/LibTAPITblgen_jll.jl/releases/download/v1300.6.1-GCCBootstrap-x86_64-linux-gnu/LibTAPITblgen-extract_log-v1300.6.1-x86_64-linux-gnu.tar.gz"
